/*
  Dependencia de reportes bitácora (tipos 2, 3, 5).
  Origen: QA_MONITOR_ATT_remediado.sql — VW_BD_TRANSACCIONES_CONCILIACION

  Aplicar si GENERAR_REPORTE falla con:
    Invalid object name 'dbo.VW_BD_TRANSACCIONES_CONCILIACION'
*/

USE [QA_MONITOR_ATT];
GO

IF OBJECT_ID(N'dbo.VW_BD_TRANSACCIONES_CONCILIACION', N'V') IS NOT NULL
BEGIN
    PRINT N'dbo.VW_BD_TRANSACCIONES_CONCILIACION ya existe.';
    RETURN;
END;
GO

CREATE VIEW [dbo].[VW_BD_TRANSACCIONES_CONCILIACION]
AS
SELECT
    B.ID_TRANSACCION,
    B.EP,
    UPPER(LTRIM(RTRIM(CONVERT(VARCHAR(50), B.EP)))) AS EP_NORM,
    B.CLIENTE,
    LTRIM(RTRIM(CONVERT(VARCHAR(100), B.CLIENTE))) AS CLIENTE_NORM,
    B.MONTO,
    TRY_CONVERT(DECIMAL(18, 2), B.MONTO) AS MONTO_NORM,
    B.FECHA,
    N.FECHA_DT,
    CASE
        WHEN N.FECHA_DT IS NULL THEN NULL
        ELSE DATEADD(
            MINUTE,
            DATEDIFF(MINUTE, CONVERT(DATETIME2(0), '19000101'), N.FECHA_DT),
            CONVERT(DATETIME2(0), '19000101'))
    END AS FECHA_OPERACION_MINUTO,
    B.TIPO,
    B.ESTATUS,
    TRY_CONVERT(INT, B.ESTATUS) AS ESTATUS_INT,
    B.TIPO_PAGO,
    B.FOLIO,
    B.CAMBIO,
    B.CAMBIO_INCOMPLETO,
    B.CODIGO_ERROR,
    B.MOTIVO_RECHAZO,
    B.DN,
    B.CODIGO_AUTORIZACION,
    B.NO_TARJETA,
    B.REFERENCIA,
    B.REFERENCIA_EP,
    B.COLOR,
    B.JOURNAL,
    B.FECHA_REGISTRO
FROM dbo.BD_TRANSACCIONES B
CROSS APPLY (
    SELECT FECHA_TXT = LTRIM(RTRIM(CONVERT(VARCHAR(200), B.FECHA)))
) S
CROSS APPLY (
    SELECT FECHA_FLOAT = TRY_CONVERT(FLOAT, REPLACE(S.FECHA_TXT, ',', '.'))
) F
CROSS APPLY (
    SELECT FECHA_DT =
        COALESCE(
            TRY_CONVERT(DATETIME2(0), S.FECHA_TXT, 120),
            TRY_CONVERT(DATETIME2(0), S.FECHA_TXT, 121),
            TRY_CONVERT(DATETIME2(0), S.FECHA_TXT, 126),
            TRY_CONVERT(DATETIME2(0), S.FECHA_TXT, 103),
            TRY_CONVERT(DATETIME2(0), S.FECHA_TXT, 105),
            CASE
                WHEN F.FECHA_FLOAT BETWEEN 20000 AND 90000 THEN
                    DATEADD(
                        SECOND,
                        CONVERT(INT, ROUND((F.FECHA_FLOAT - FLOOR(F.FECHA_FLOAT)) * 86400, 0)),
                        DATEADD(
                            DAY,
                            CONVERT(INT, FLOOR(F.FECHA_FLOAT)),
                            CONVERT(DATETIME2(0), '18991230')))
                ELSE NULL
            END)
) N;
GO

PRINT N'OK: VW_BD_TRANSACCIONES_CONCILIACION creada.';
GO
