/*
  Referencia de contrato para ATT.Monitor.Api → DashboardDataService.UpsertDetalleEquipoSoDdFromAgentAsync

  Si su procedimiento ya existe con otros nombres de parámetro, alinée el SP o el objeto anónimo en C#.

  Dapper envía:
    @ID_ATM, @ID_SESION, @SISTEMA_OPERATIVO, @MEMORIA_RAM, @IDIOMA, @RESOLUCION, @PROCESADOR,
    @NOMBRE_DE_WINDOWS, @ZONA_HORARIA, @NOMBRE_EQUIPO_SO, @UNIDAD_DISCO_DURO, @TAMANHO_DISCO_DURO, @ESPACIO_LIBRE_DD
*/

IF OBJECT_ID(N'dbo.SP_DETALLE_EQUIPO_UPSERT_SO_DD_ON_START', N'P') IS NULL
    EXEC(N'CREATE PROCEDURE dbo.SP_DETALLE_EQUIPO_UPSERT_SO_DD_ON_START AS SET NOCOUNT ON;');
GO

ALTER PROCEDURE dbo.SP_DETALLE_EQUIPO_UPSERT_SO_DD_ON_START
    @ID_ATM              NVARCHAR(64),
    @ID_SESION          UNIQUEIDENTIFIER NULL,
    @SISTEMA_OPERATIVO  NVARCHAR(500) NULL,
    @MEMORIA_RAM        FLOAT NULL,
    @IDIOMA             NVARCHAR(200) NULL,
    @RESOLUCION         NVARCHAR(200) NULL,
    @PROCESADOR         NVARCHAR(500) NULL,
    @NOMBRE_DE_WINDOWS  NVARCHAR(500) NULL,
    @ZONA_HORARIA       NVARCHAR(200) NULL,
    @NOMBRE_EQUIPO_SO   NVARCHAR(260) NULL,
    @UNIDAD_DISCO_DURO  NVARCHAR(50) NULL,
    @TAMANHO_DISCO_DURO NVARCHAR(200) NULL,
    @ESPACIO_LIBRE_DD   NVARCHAR(200) NULL
AS
BEGIN
    SET NOCOUNT ON;
    /* Implementar MERGE/UPDATE en tablas usadas por FN_GET_EQUIPOSDETALLE_SO / FN_GET_EQUIPOSDETALLE_DD */
END
GO
